name: Rust Monorepo CI (Windows)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[SKIP CI]')"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Install Protoc
      uses: arduino/setup-protoc@v3

    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build all tools
      shell: bash
      run: |
        cd tools
        for tool in */; do
          tool=${tool%/}
          echo "Building tool: $tool"
          cargo build --package $tool
        done

    # - name: Run tests for all tools
    #   shell: bash
    #   run: |
    #     cd tools
    #     for tool in */; do
    #       tool=${tool%/}
    #       echo "Testing tool: $tool"
    #       cargo test --package $tool
    #     done

    - name: Upload artifacts for all tools
      uses: actions/upload-artifact@v3
      with:
        name: ${{ runner.os }}-tools
        path: |
          target/debug/*.exe
        if-no-files-found: error
